### ISSUE TITLE
'USB error: Resource busy' on first use

### ISSUE THREAD

**Issue by Frederick888** [wisespace-io/yubico-manager#2]
I'm using this library in a CLI tool that I developed:

https://github.com/Frederick888/git-credential-keepassxc/blob/fa669994c7bd3dd6673a6b7a2d1f9b7d0ddeeb1f/src/config.rs#L118-L142

A weird issue I noticed is that, after my YubiKey is plugged in, it always fails with `USB  error: Resource busy` for the first time. This issue doesn't happen to the official `ykchalresp`.

I'm running Arch Linux with `libusb 1.0.23-2`. The firmware version of my YubiKey is 5.1.2.

**Comment by Frederick888** [comment]
Same issue happens to the HMAC-SHA1 example as well:

```sh
$ export RUST_BACKTRACE=full
$ ./target/debug/examples/challenge_response_hmac
Vendor ID: 4176 Product ID 1031
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UsbError(Busy)', examples/challenge_response_hmac.rs:24:25
stack backtrace:
   0:     0x55a3e84ff324 - backtrace::backtrace::libunwind::trace::hc1c4a1d8ad423b97
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x55a3e84ff324 - backtrace::backtrace::trace_unsynchronized::h82274781060cb056
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x55a3e84ff324 - std::sys_common::backtrace::_print_fmt::h2a45d89b653a4da8
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55a3e84ff324 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h41a0a93ab85e6aa1
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55a3e851ce1c - core::fmt::write::hdaea18585065a96d
                               at src/libcore/fmt/mod.rs:1069
   5:     0x55a3e84fd843 - std::io::Write::write_fmt::h0cea70c809005252
                               at src/libstd/io/mod.rs:1504
   6:     0x55a3e85018c5 - std::sys_common::backtrace::_print::hd95f9978cc145ca4
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55a3e85018c5 - std::sys_common::backtrace::print::hfb25ca2291be47d0
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55a3e85018c5 - std::panicking::default_hook::{{closure}}::h44f76cee5dc8591c
                               at src/libstd/panicking.rs:198
   9:     0x55a3e8501602 - std::panicking::default_hook::h198e1a712910f1e6
                               at src/libstd/panicking.rs:218
  10:     0x55a3e8501ed2 - std::panicking::rust_panic_with_hook::hc0b4730bb8013f9d
                               at src/libstd/panicking.rs:511
  11:     0x55a3e8501abb - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  12:     0x55a3e851c201 - core::panicking::panic_fmt::h1ac71ad045d55416
                               at src/libcore/panicking.rs:111
  13:     0x55a3e851c023 - core::option::expect_none_failed::hb40004d71d61b685
                               at src/libcore/option.rs:1268
  14:     0x55a3e84e1332 - core::result::Result<T,E>::unwrap::hf6c892de97227ffa
                               at /home/frederick/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/result.rs:1005
  15:     0x55a3e84e192b - challenge_response_hmac::main::hafe411dd18680ea4
                               at examples/challenge_response_hmac.rs:24
  16:     0x55a3e84e1e2b - std::rt::lang_start::{{closure}}::h6f22a5bbe242bcf6
                               at /home/frederick/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  17:     0x55a3e8502318 - std::rt::lang_start_internal::{{closure}}::h7a212202ff76034b
                               at src/libstd/rt.rs:52
  18:     0x55a3e8502318 - std::panicking::try::do_call::h6d214a73427d759b
                               at src/libstd/panicking.rs:331
  19:     0x55a3e8502318 - std::panicking::try::hc078f0e11721d1cb
                               at src/libstd/panicking.rs:274
  20:     0x55a3e8502318 - std::panic::catch_unwind::hb31c05be30625612
                               at src/libstd/panic.rs:394
  21:     0x55a3e8502318 - std::rt::lang_start_internal::hcf7fb98a775d5af0
                               at src/libstd/rt.rs:51
  22:     0x55a3e84e1e07 - std::rt::lang_start::h9a765ee239fadf68
                               at /home/frederick/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  23:     0x55a3e84e1b7a - main
  24:     0x7f9501eb0002 - __libc_start_main
  25:     0x55a3e84e117e - _start
  26:                0x0 - <unknown>
```
